### ISSUE TITLE
[BugFix] Scroll in the stories thumbnails

### ISSUE THREAD

**Issue by pmarquees** [CaliAlec/ChromeIGStory#1]
I have a lot of Instagram friends, and I just did a fix, because for me it was showing a huge list with all my friends.

Now it looks like this.

Is it a bug just for me? Should I merge this?

This is how it looks after my fix with a side scroll, just like the app.

![giphy](https://cloud.githubusercontent.com/assets/2625083/17591774/e0c369ac-5fdf-11e6-80ad-6ab20352852a.gif)

**Comment by CaliAlec** [comment]
@pmarquees Thank you, it was an oversight on my end. I didn't have enough friends with Stories at the time and didn't foresee the issue. Your fix nicely mimics the behavior in the mobile app. 👍
