### ISSUE TITLE
failing layout

### ISSUE THREAD

**Issue by ViperCode7** [CaliAlec/ChromeIGStory#104]
In the popout version the images were always larger than the preview screen, hence to see them the user has to scroll them. Now as I've seen the modal window version does the same, but lacks scrolling functionality. This issue stems from the fact that not all images have the right proportions, some have less width than others so when the viewer resizes them based on width only, the become "very long" and out of view. A proposition to resize images in the viewer based on both width and height and fill the background with a color, or a blurred version of the enlarged image etc. This way wide images will have top and bottom bars and tall images will have side bars, but both will be into view. No scrolling needed.

**Comment by CaliAlec** [comment]
Fixed in v2.2.0
