### ISSUE TITLE
Dont like the newest update :(

### ISSUE THREAD

**Issue by Methennow** [CaliAlec/ChromeIGStory#107]
I acctually hate the newest update, people want the app to be easier, and easier to mass-download.
With this newest update, It will take for ever to download MANY stories.

Instead you should still fix the "download all stories" like I have wanted before :)

Thanks for an good app, and good job, but please dont make it worse and worse :)

**Comment by ricardokdz** [comment]
+1

**Comment by adamjapon** [comment]
Up up up.....
Cmon @CaliAlec bring back the old version ~
