### ISSUE TITLE
No view created

### ISSUE THREAD

**Issue by alikabeel** [CaliAlec/ChromeIGStory#12]
How can the extension get the media without creating a view urgent please
thanks

**Comment by CaliAlec** [comment]
@alikabeel What do you mean by "without creating a view"? Do you mean a popup? Chrome extensions don't have to have a popup. This extension makes use of a background script and content_scripts to inject the media into the page. Checkout js/injectStoryTray.js to see how it's done.

**Comment by alikabeel** [comment]
i mean that the story does not appear as viewed i have downloaded a story but still it appears as new how is this done?

**Comment by CaliAlec** [comment]
@alikabeel Oh, I was confused for a second. The Instagram app makes a request to `https://i.instagram.com/api/v1/media/seen/` after you view a Story. This extension simply doesn't call that endpoint.
