### ISSUE TITLE
Nothing works. 

### ISSUE THREAD

**Issue by duttaditya18** [CaliAlec/ChromeIGStory#129]
Everything just keeps on loading. Doesn't work.

**Comment by RaekenDE** [comment]
Working fine to me. Try to uninstall and install again.

By the way, it's sad that Alec seems to stopped working on this extension. Looks like abandoned.

**Comment by duttaditya18** [comment]
@RaekenDE No it doesn't. I am on Firefox and am using it with [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/).

I am currently using a sort of working setup with [instaloader/instaloader](https://github.com/instaloader/instaloader) to view stories without letting the other person know. I am thinking of making a desktop app.
