### ISSUE TITLE
The app keeps Crashing and requesting me to sign in again 

### ISSUE THREAD

**Issue by myketaz85** [CaliAlec/ChromeIGStory#130]
The app keeps crashing and requesting me to sign in again?

**Comment by kyi561** [comment]
I am having this too, it's very frustrating

**Comment by Soul199** [comment]
same problem here :)

**Comment by kjaerlige** [comment]
I fixed this issue by going to extensions' settings - Permissions:
Allow this extension to read and change all your data on websites you visit: [switch to "On all sites"]
