### ISSUE TITLE
Can't view any stories, extension closes itself

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [CaliAlec/ChromeIGStory#134]
As of today, this extension seems to be almost completely broken.
Instead of displaying a story, it always closes itself.
The option to download story highlights also doesn't seem to exist anymore.
The only thing that still works is the download of current stories as a .ZIP archive. But even this now has problems, because you have to reload the extension after every download, since it always crashes.

**Comment by happycheeseburger** [comment]
Same happening here cant download but needs to be restarted each time and it just crashes when trying to view stories

**Comment by darkbondd** [comment]
Same thing here

**Comment by happycheeseburger** [comment]
A comment further down adds that the person who made the app Alec seems to have abandoned working on the app so it may be left to die and that why it's no longer working right. No one to update it to work as instagram makes new changes.

**Comment by ViperCode7** [comment]
Good to hear. So the main page loads, it updates all of the people with new stories but when clicking on it I get several errors in the console window.

[bojgejgifofondahckoaahkilneffhmf-1536291688637.log](https://github.com/CaliAlec/ChromeIGStory/files/2359401/bojgejgifofondahckoaahkilneffhmf-1536291688637.log)

Might the "429 (TOO MANY REQUESTS)" bit have anything to do with it?

**Comment by Schknheit** [comment]
Cali, could you add an option to download everyones stories like you did to download them individually? I follow a big amount of artists and having to download one by one is time consuming. I wish I could help you do it but I dont know how to program ;(

**Comment by happycheeseburger** [comment]
Thats good to hear hope it can be fixed this app comes in handy to save and view stories

**Comment by happycheeseburger** [comment]
How is this closed it's still crashing.
