### ISSUE TITLE
Can´t be watching stories user's profile page?

### ISSUE THREAD

**Issue by hdgalarza** [CaliAlec/ChromeIGStory#14]
Hello.
When i charge a instagram user profile i received this message

Failed to load resource: the server responded with a status of 400 ()
injectStoryTray.js:90 Error loading Story for user: ""

I´m tried to change the var userid for other variabilities but still cant function
![image](https://cloud.githubusercontent.com/assets/23296066/20039517/43f03dc6-a413-11e6-8869-d36e91b0097d.png)

**Comment by PedroAlbR** [comment]
I made the request by myself and got this message: `{
"status": "fail",
"message": "login_required"
}`
