### ISSUE TITLE
SAME OLD ISSUE, PLEASE, HELP! 

### ISSUE THREAD

**Issue by mrzuliani** [CaliAlec/ChromeIGStory#142]
I can't download anymore. Every time I try, the application closes itself and ask me to login again on instagram.

**Comment by Alex220** [comment]
Disable **"Anonymous viewing enabled"** to solve the problem.

**Comment by shahmoradi21** [comment]
mute the thread

    On Friday, December 28, 2018, 8:18:26 p.m. GMT+3:30, Alex220 <notifications@github.com> wrote:  
 
 
Disable "Anonymous viewing enabled" to solve the problem.
