### ISSUE TITLE
Check instagram cookies validity

### ISSUE THREAD

**Issue by sbala69gmail** [CaliAlec/ChromeIGStory#144]
I can retrieve two Instagram cookies  ‘ds_user_id’ and ‘sessionid’ using the ‘chrome.cookies’ API and then inject them into our request’s headers.

so kindly help how to check  instagram cookies validity ?

**Comment by sbala69gmail** [comment]
Hi,
   we found the solutions,Thank you.

**Comment by CaliAlec** [comment]
@sbala69gmail What did you end up doing?
