### ISSUE TITLE
Instagram live?

### ISSUE THREAD

**Issue by tbwktm** [CaliAlec/ChromeIGStory#19]
Hello!

I really love your application, it's an amazing way to watch the instagram stories! Do you think you could add the instagram lives too?

Thanks in advance!

**Comment by CaliAlec** [comment]
@tbwktm Currently you can watch Instagram Live Videos on Matcha (https://watchmatcha.com/) which I am developing as a better version of Chrome IG Story. I'll consider adding Live Videos support to this extension as well.

**Comment by tbwktm** [comment]
@CaliAlec Amazing, thank you so much!

**Comment by bamtan** [comment]
How about Live stories? Like public broadcast stories
