### ISSUE TITLE
Please change it back.

### ISSUE THREAD

**Issue by AlicesWrath** [CaliAlec/ChromeIGStory#25]
The new update is just awful.

Why does it open in a new window? Why is there no ability to pause a video? Why is there a timer before it auto scrolls to the next one? Why is there no ability to go back and forth?

I appreciate wanting to keep the app fresh, but you've turned what was an extension that worked perfectly into one that is terrible and as you can see from the recent reviews on the Chrome store, I'm not alone in thinking this.

Please change it back. Or at least create a separate version.

**Comment by tdkl** [comment]
Indeed, this is a horrible change. Also the permission to view the browser history is unwelcomed.

**Comment by CaliAlec** [comment]
Ya'll savage af 😂😂😂

**Comment by avm99963** [comment]
Hi!

I'm also worried about the "tabs" permission and other similar ones, so if you want I'll try to have a look in order to see if it's possible to make a pull request in which I take out the "tabs" permissions and make the extension work without it.

Also, I'll try to make the content script not persistent so it doesn't consume that much memory.

What do you think?

**Comment by tdkl** [comment]
Thing is, that this isn't just a version change update. It's a completely different thing all around. It behaves and runs differently. It's like taking a car in a shop for an update and the end result is a submarine. Of course users aren't going to be happy. 

IMHO with a change so drastic it would be better to ship this as a separate extension calling it Chrome IG Story Live (since this was a requested feature) and keep the previous version as it is.

**Comment by CaliAlec** [comment]
Guys, this is GitHub, you can create a branch yourself based on the old commit and recompile a version that you like. I only pushed the update to 5% of my users ~20k to see the response, and I've learned it's not great. I'll be working to revert the part that forces the popup to open when you click on a story on the Instagram website but I'm still going to keep the popup.

**Comment by tdkl** [comment]
Even better, I hope someone will fork and re-release the old version in the Chrome Web Store as a new  extension, because this is GitHub. So all the users in Chrome Web Store who don't like the change and can't recompile their own versions can switch to that.

**Comment by avm99963** [comment]
@CaliAlec I think that would be a great idea, maintain the old version behaviour but also include the popup 😃 

BTW, what do you think about trying to reduce the number of permissions the extension asks without losing any functionality? I'm pretty sure there are permissions which are redundant and that we could remove. I think asking to "access all sites" is quite scary and maybe there's a way to show the stories and not lose any functionality without requesting this permission hehe

I have experience building extensions trying to keep the minimum permissions possible so I can help with that.

**Comment by CaliAlec** [comment]
@avm99963 The only permission that was added was "tabs" and it wasn't even needed so I removed it.

**Comment by CaliAlec** [comment]
https://github.com/CaliAlec/ChromeIGStory/commit/29160c6b23e8eb16b4dda2fce4129a29492ced1b

**Comment by Vaadims** [comment]
heeey(  i want to see a story without follow( bring it back please!

**Comment by AlicesWrath** [comment]
> Guys, this is GitHub, you can create a branch yourself based on the old commit and recompile a version that you like.

I would do this if I knew how. Could someone else?

**Comment by CaliAlec** [comment]
@AlicesWrath This is already fixed on the v2.0.2 version on the Chrome Web Store.

**Comment by AlicesWrath** [comment]
@CaliAlec Ah sorry, hadn't updated yet. Thanks. 

One minor thing, would it be possible to add back the left and right buttons to scroll through stories instead of having to click and drag through them?

**Comment by tdkl** [comment]
Thank you for the 2.0.2 version and reverting the changes. I can't get the story indicators to be marked as read though, also hidden user stories are visible, so it completely disregards the state in the mobile app. Also tried logging out of the web and mobile, but it's the same. This functioned before the 2.x change.

**Comment by Vaadims** [comment]
hm...  i have a strage thing.

i have a two computer, but this plugin work not the same( 
on my pc i can see a story from any users. on my laptop-i can't do it
