### ISSUE TITLE
How to Download Individual Stories on Version 2.0.2

### ISSUE THREAD

**Issue by amalla1970** [CaliAlec/ChromeIGStory#28]
How to Download Individual Stories on Version 2.0.2
Usually i went to the persons page and right click but on version 2.0.2 i can view the storie is possible but cant save it anymore to view it later

Great work

**Comment by Firemandude** [comment]
Is anyone able to view a specific user's stories by going to that user's profile page on IG Story? Cause if this feature exists, it doesn't seem to work for me. 

If that feature doesn't exist, it would be very much welcomed as not all stories of the people I follow show up on my feed.

Thanks!

**Comment by amalla1970** [comment]
In older version worked. it had a red ring when it had a Story, then the ring was removed but it still worked.  After the version 2.0.2 was introduced it stopped working.
I liked it a lot

**Comment by CaliAlec** [comment]
I'll​ be working on fixing all the issues this weekend. I'm also working on
something similar for Messenger Day.

**Comment by amalla1970** [comment]
Kool, I would give you my feedback after its released.

Have a great Weekend

**Comment by amalla1970** [comment]
Hi Alec have you made any progress on this? I like the feature of downloading to a Zip file
To Right Clic on an persons instagram to redownload

**Comment by ivanala** [comment]
Hi Alec, Do you know anything new on this issue?

Great extension!!

**Comment by CaliAlec** [comment]
Fixed in https://github.com/CaliAlec/ChromeIGStory/commit/b4034d40008fcce82464358f629aa18b718b37f1
