### ISSUE TITLE
Feature Request - A Download Icon of the Story in Story Mode

### ISSUE THREAD

**Issue by amalla1970** [CaliAlec/ChromeIGStory#29]
Feature Request - A Download Icon of the Story in Story Mode.
In Story Mode you have Full Screen, Download current Story.
A link to go to the person Instagran and also an Icon or Link to download the Full Story would be much apreciated.

Keep on the with your good ideas

**Comment by CaliAlec** [comment]
Added in https://github.com/CaliAlec/ChromeIGStory/commit/afb69e916c1f3e82e7ffd2cd8b97fc6fc2df6bca
