### ISSUE TITLE
Current Version (2.0.1 & 2.0.2) Breaks Instagram

### ISSUE THREAD

**Issue by malcalevak** [CaliAlec/ChromeIGStory#30]
So it took me a second to realize this extension was at fault, but it appears Instagram likely changed something about their page that, in addition to preventing this extension from opening its window, is preventing me from properly hearting posts. I appear able to heart a post, but if I refresh the page, or check it elsewhere I'll find it's no longer hearted.

Edit: Right after I posted, I tried again, and the hearting was working, weird. The rest is still broken.

**Comment by kurtextrem** [comment]
If you use `Improved Layout for Instagram` it should fix the issue.
