### ISSUE TITLE
how do i download an expired instastory using chromeigstory?

### ISSUE THREAD

**Issue by krnsdh** [CaliAlec/ChromeIGStory#31]
Hi CaliAlec,

Sorry, I do not understand code but really need to retrieve an expired instastory that wasn't saved.

Is there a way that this can be done using the extension? How so? Perhaps I can provide you with the instagram username and you could assist?

Thank you so much.

**Comment by CaliAlec** [comment]
Once a story is expired, there's no way to retrieve it.
