### ISSUE TITLE
Stories aren't marked as seen on the web, despite being so on the phone

### ISSUE THREAD

**Issue by tdkl** [CaliAlec/ChromeIGStory#36]
> Currently, Chrome IG Story does not mark the Story as being "seen", so all new content will remain new if you view it with this extension. If you view that user's Story on your phone and refresh the page, the new content will be gray.

This doesn't work as intended from 2.x and on, all stories are marked as seen on the phone, but on the web they're always with the red border. I've reinstalled the extension from the Chrome Store, but same behaviour persists.

**Comment by CaliAlec** [comment]
@tdkl Ah, this needs to be fixed. Before, I was dynamically swapping the CSS class if the story had new items or not. Forgot to port this functionality when I switched to React.

**Comment by tdkl** [comment]
@CaliAlec I see, thanks for the quick acknowledgment of the issue, hope it'll be done eventually, it's quite confusing seing all the stories red on the web all the time.

**Comment by CaliAlec** [comment]
Fixed in https://github.com/CaliAlec/ChromeIGStory/commit/7cfb365ee0447d291a72cf9832d254d6e986a4d6
