### ISSUE TITLE
add buttons for navigation

### ISSUE THREAD

**Issue by onhernandes** [CaliAlec/ChromeIGStory#39]
Add buttons for navigation through the stories would be helpful. Prev/next/exit, I think they are enough

And, what do you think about auto-switch between stories?

Removing the color-border around the profile pic when the story is already viewed.

I'm learning more about chrome extensions and I'll try to help with these things!

**Comment by CaliAlec** [comment]
Added next/previous buttons in https://github.com/CaliAlec/ChromeIGStory/commit/69b8c3b6f77923e60717be6a0b67737e534a7ced and removed the color-border for viewed stories in https://github.com/CaliAlec/ChromeIGStory/commit/7cfb365ee0447d291a72cf9832d254d6e986a4d6
