### ISSUE TITLE
Particular users' Stories

### ISSUE THREAD

**Issue by danieman** [CaliAlec/ChromeIGStory#41]
Hi, 

the plugin lets you view the stories of the persons you follow, aswell as a selection of celebrities and other randoms in the Explore tab. Could you please also add support for other particular users as well? I'd like to see the Story of a particular user without having to follow him first.

I thought it would be fairly trivial to fix with the getStory-function in utils/InstagramApi.js, but apparently I didn't have the skills needed to pull it off. :) An update or a push in the right direction would be much appreciated! Thanks!

**Comment by CaliAlec** [comment]
Added user search in https://github.com/CaliAlec/ChromeIGStory/commit/bb795cf7b78494d7cfc286f1bd40a8db870df2b7

**Comment by danieman** [comment]
Thanks!! Is it only for viewing? I'm able to _view_ the story of users I don't follow by visiting their profile, and clicking on their profile picture, but I haven't been able to figure out how to _download_ the story of a user I don't follow yet. Is that possible in any way? For example by letting us add unfollowed users to our "friend list" in the popup, or adding a download button when displaying the stories?

**Comment by CaliAlec** [comment]
@danieman I added a download button on the story itself in https://github.com/CaliAlec/ChromeIGStory/commit/afb69e916c1f3e82e7ffd2cd8b97fc6fc2df6bca and download buttons in the search result lists (https://github.com/CaliAlec/ChromeIGStory/commit/a84c83c02ca8263cf2c84f65b6b5c7cb7312c43d) so you can search for a user and download their story even if you don't follow them.
