### ISSUE TITLE
Fix that please!

### ISSUE THREAD

**Issue by Pandorablue** [CaliAlec/ChromeIGStory#42]
Yesterday the extension worked (almost) perfectly, I can saw someone's story in their profile even the ig stories ring was hidden apart if I wasn't following them.. But now I can't see the stories in their profiles, just in the newsfeed and THERE EVEN CAN'T SEE ALL OF THE STORIES. Fix that quickly, I want to see someone's stories in their profiles again.

**Comment by CaliAlec** [comment]
Fixed in https://github.com/CaliAlec/ChromeIGStory/commit/92e56521c16a6bc969b336200215f8e95f66a0cb
