### ISSUE TITLE
400 Error when attempting to view a story from a users page

### ISSUE THREAD

**Issue by tyronedougherty** [CaliAlec/ChromeIGStory#44]
When attempting to view a users story from their user page it does not work and instead produces a `400` return.

For example, visiting https://www.instagram.com/diplo/ will return this error:

<img width="1434" alt="screen shot 2017-08-02 at 10 50 00 am" src="https://user-images.githubusercontent.com/4608024/28852969-6c93fb1a-7770-11e7-82c7-de400efc5026.png">

This is the response from the API at `https://i.instagram.com/api/v1/feed/user/189802609/reel_media/`:

```
{"message": "login_required", "logout_reason": 2, "status": "fail"}
```

I guess the request is not being signed or something?

**Comment by CaliAlec** [comment]
@tyronedougherty Did you pull from master and are you on the latest version (2.1.1)? If works fine for me.
<img width="1712" alt="screen shot 2017-08-01 at 5 56 31 pm" src="https://user-images.githubusercontent.com/2003684/28853090-ecb131d4-76e2-11e7-9fa4-d2ee4cbe92d1.png">

**Comment by tyronedougherty** [comment]
Oops, seems like I was on an older version! Fixed in latest 👍

**Comment by CaliAlec** [comment]
@tyronedougherty 👊👊👊
