### ISSUE TITLE
About live video

### ISSUE THREAD

**Issue by Pandorablue** [CaliAlec/ChromeIGStory#47]
Since ig stories saves now your live video, How about allowing to download it from desktop too like regular videos and pictures? It will be awesome really :D

**Comment by CaliAlec** [comment]
This was added in https://github.com/CaliAlec/ChromeIGStory/commit/c1c22cfda50b3ed6e1c62c3cab5005518e2ce1d0

**Comment by Pandorablue** [comment]
but still don't let me like regular videos or pictures

**Comment by Pandorablue** [comment]
I mean, the videos went all black
