### ISSUE TITLE
Progress-bar for static stories (photos) in website

### ISSUE THREAD

**Issue by AlexWayfer** [CaliAlec/ChromeIGStory#53]
Hello (again).

In extension window photo-stories have a progress-bar (with some time, about 3 seconds).

![image](https://user-images.githubusercontent.com/6510020/29588672-197de540-879b-11e7-8d15-f690538eeaae.png)

What about add the same progress-bar to the Instagram website?

![image](https://user-images.githubusercontent.com/6510020/29588692-2649148e-879b-11e7-89e6-1198038daa74.png)

Thank you.

**Comment by CaliAlec** [comment]
@AlexWayfer The progress bars were from back when the story automatically progressed, so right now they are messed up when you manually switch to the next photo/video. I need to do some refactoring on the progress bar logic, then I will add it to the gallery that is injected into the website.

**Comment by AlexWayfer** [comment]
So… Some refactoring done? Progress bar is there? Why issue is closed?

**Comment by CaliAlec** [comment]
@AlexWayfer Starting from v2.2, the Story.js component includes the StoryProgress.js component. The stories are no longer shown in a popup/modal; instead, they are injected directly into the Instagram page.

**Comment by AlexWayfer** [comment]
Okay, thank you! It's just for clarity.
