### ISSUE TITLE
Link to the extension on Chrome Web Store

### ISSUE THREAD

**Issue by AlexWayfer** [CaliAlec/ChromeIGStory#55]
Hello!

I found [your extension on Chrome Web Store](https://chrome.google.com/webstore/detail/chrome-ig-story/bojgejgifofondahckoaahkilneffhmf) manually, but for others it may be much more convenient to go directly from repo description (under the repo title) or `README`.

Thank you!

**Comment by CaliAlec** [comment]
Added in https://github.com/CaliAlec/ChromeIGStory/commit/7a1543676ba990d24a17833b6750a1d746ab672d
