### ISSUE TITLE
Chrome Ig Story loading in loop

### ISSUE THREAD

**Issue by iPicoStick** [CaliAlec/ChromeIGStory#58]
Hi.
I've noticed when i try to open the applications, the loading is in loop.
I can't see anything...what can I do for solve it? 

Thanks in advance 
![ig](https://user-images.githubusercontent.com/31159145/29619293-0e0f449e-881b-11e7-9efe-6b9e9618fad5.png)

**Comment by DANIEL120321** [comment]
same to me

**Comment by iPicoStick** [comment]
thanks for reply Daniel, from where can i login on my insta account?

thanks in advance

**Comment by DANIEL120321** [comment]
go to https://www.instagram.com/ and login. after that u need to see all of th story.

**Comment by CaliAlec** [comment]
@iPicoStick are you able to see your stories now?
