### ISSUE TITLE
Chrome IG Story not loading 

### ISSUE THREAD

**Issue by PPDolce** [CaliAlec/ChromeIGStory#59]
I'm logged in and all I constantly see is looping

**Comment by The-KarateKid** [comment]
I've encountered this as well. I found that if I refresh the page a few times (sometimes a Hard Refresh is needed) it eventually loads.

**Comment by CaliAlec** [comment]
@PPDolce are you able to see your stories after logging out and back in to Instagram.com?

**Comment by andrewhendersons** [comment]
Why are some instagram live videos not saved? in order to watch replays
