### ISSUE TITLE
The stories are bigger then page height, partially visible.

### ISSUE THREAD

**Issue by GrayFace** [CaliAlec/ChromeIGStory#60]
After the last update depending on Zoom level the stories are bigger or smaller (in case of negative zoom) then the page. The same issue has always been the case in popup window and live recordings.

**Comment by GrayFace** [comment]
Moreover, height changes from story to story.

**Comment by GrayFace** [comment]
Another newly introduced bug: video controls on some stories being stretched to whole screen horizontally, making it impossible to click anywhere.
And bug 3: it no longer can be dragged by holding the mouse anywhere, now I have to place the mouse precisely above the video.

My current partial fix for bugs 1 and 2:
.image-current video {
    max-height: 100vh !important;
    max-width: 70vh !important;
    margin: auto !important;
}

This fix however makes it impossible to drag the thing at all.

**Comment by anthonywjuvw** [comment]
im new user.
how i can fix? where i have to paste them?
sorry fo my english.

**Comment by ssd90** [comment]
Video stories always longer than height. I'm trying height: 100vh; and work for me.

**Comment by GrayFace** [comment]
@anthonywjuvw You'd need Stylish extension, then go to Instagram an create a style for it with this code. Once the problem is fixed in the extension you'll need to delete the style.

**Comment by CaliAlec** [comment]
Fixed in https://github.com/CaliAlec/ChromeIGStory/commit/4031045ea0629b7a07e57d13ecd11f74c0d70edc

**Comment by anthonywjuvw** [comment]
thanks.
