### ISSUE TITLE
Stories started playing on loop with the last update.

### ISSUE THREAD

**Issue by GrayFace** [CaliAlec/ChromeIGStory#61]
One story playing indefinitely (bad) instead of either stopping (ok) or switching to the next story of the person (better).

**Comment by CaliAlec** [comment]
@GrayFace The videos are meant to loop. The trend on the web now is to loop video. Facebook and even Instagram loop videos in the app. I know Instagram does't loop videos for stories, but the point of the gallery in this extension is to view the current story as if it was a photo gallery, so the user should be able to watch it as long as they wish. I'm going to add a feature soon to autoplay all stories so they advance to the next story just like the app.
