### ISSUE TITLE
Add name of the user to the <div> as id

### ISSUE THREAD

**Issue by kurtextrem** [CaliAlec/ChromeIGStory#68]
That would make it possible to 'block' storys using an adblocker.

**Comment by CaliAlec** [comment]
Sorry, I don't understand the purpose of this. Are you saying that Chrome IG Story is blocked by AdBlocker?

**Comment by kurtextrem** [comment]
No. The change makes it possible to hide stories. 
e.g. I follow a lot of ppl and I don't want to see every story. So using an adblocker I could then hide the element and therefor the users I don't want to see.

**Comment by CaliAlec** [comment]
Added in https://github.com/CaliAlec/ChromeIGStory/pull/69
