### ISSUE TITLE
would it be possible to see views?

### ISSUE THREAD

**Issue by glentennis** [CaliAlec/ChromeIGStory#7]
Hello,

I'm wondering if it would be possible to see the number of views a story is getting. Lemme know!

Best,
Geoff

**Comment by CaliAlec** [comment]
@glentennis It's only possible to see the people who have viewed your own Story.

**Comment by glentennis** [comment]
is this viewable on desktop through your extension?

**Comment by CaliAlec** [comment]
@glentennis Do you want to see just view count or the actual usernames of the viewers, or both? I can add it to the extension.

**Comment by felipeilha** [comment]
Yes please! Add them both.
