### ISSUE TITLE
Instagram video stories are not loading in the app

### ISSUE THREAD

**Issue by jeremyjohn** [CaliAlec/ChromeIGStory#70]
![screenshot from 2017-09-14 12-02-41](https://user-images.githubusercontent.com/12860603/30411607-a23e2ae2-9944-11e7-84a0-9eaa77bfcb7a.png)

**Comment by CaliAlec** [comment]
Fixed in https://github.com/CaliAlec/ChromeIGStory/pull/73 and in Chrome Web Store version 2.1.5
