### ISSUE TITLE
Download Stories function broken

### ISSUE THREAD

**Issue by The-KarateKid** [CaliAlec/ChromeIGStory#71]
Lately when I try to download a person's story which has videos in it, the download fails with various 403 errors. Oddly enough, the videos load fine when viewing the stories, this only happens when trying to initiate a story download. Also, this only happens on *some* stories with videos, not all of them.

> GET https://scontent-lga3-1.cdninstagram.com/v/-token-removed-/-videofilename-.mp4 403 ()

> Failed to load https://scontent-lga3-1.cdninstagram.com/v/-token-removed-/-videofilename-.mp4: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://bojgejgifofondahckoaahkilneffhmf' is therefore not allowed access. The response had HTTP status code 403.

> content.js:108717 Uncaught (in promise) Error: InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').
    at XMLHttpRequest.xhr.onreadystatechange (content.js:108717)

The "downloading pending" spinning circle keeps looping and the download never happens.

**Comment by idkwhatthisisbutok** [comment]
same.

**Comment by The-KarateKid** [comment]
@prKassad's change fixed this issue. Thanks!
