### ISSUE TITLE
downloads dont work, images and videos not loading.

### ISSUE THREAD

**Issue by qaz4321** [CaliAlec/ChromeIGStory#72]
Some images works but most are blank videos also don't work and download out right doesn't work.

**Comment by flashbax14** [comment]
same problem!

**Comment by qaz4321** [comment]
What does  it do is that the fix? I dont know any of that stuff.

**Comment by orcunas** [comment]
@CaliAlec I'm experiencing the same issue. I attached the screenshot of my extension's console, hope it helps.
![screen shot 2017-09-18 at 21 02 36](https://user-images.githubusercontent.com/2998754/30556862-f47b2c10-9cb4-11e7-9220-b32db51625d3.png)

**Comment by CaliAlec** [comment]
Fixed in https://github.com/CaliAlec/ChromeIGStory/pull/73 and in Chrome Web Store version 2.1.5
