### ISSUE TITLE
What happened to my account or broswer?

### ISSUE THREAD

**Issue by LA88** [CaliAlec/ChromeIGStory#74]
1: I tried this account on 2 computers and it's still like this.
2: IG Story works well on my other accounts ......and works well.

pic https://pbs.twimg.com/media/DJ81r0rUQAAmvvV.jpg

**Comment by prKassad** [comment]
Maybe conflicts with other extensions? Try to disable them.

**Comment by LA88** [comment]
@prKassad thank you, I tried my account on another computer which has no extensions but still like this......

**Comment by CaliAlec** [comment]
@LA88 Instagram recently officially implemented Stories on desktop, so it must be conflicting. I don't have the Stories on my desktop yet, so I can't test. Going forward, this extension will be modified to accommodate Instagram's official support.

**Comment by fanxy121** [comment]
But Why I can't see the official ig story on my desktop.Only use this extensions I can see them.
