### ISSUE TITLE
Downloads doesnt work. Help!!!! 

### ISSUE THREAD

**Issue by mrzuliani** [CaliAlec/ChromeIGStory#75]
Some images work, but most are blank videos also do not work. Download doesn't work at all. HELP ME, PLEASE!

**Comment by CaliAlec** [comment]
Fixed in https://github.com/CaliAlec/ChromeIGStory/pull/73 and in Chrome Web Store version 2.1.5

**Comment by mrzuliani** [comment]
The new version is available already?

**Comment by CaliAlec** [comment]
@mrzuliani It's propagating. Maybe in an hour or so.

**Comment by mrzuliani** [comment]
Ok. Thank you!
