### ISSUE TITLE
Can be adding class for hidden stories?

### ISSUE THREAD

**Issue by ssd90** [CaliAlec/ChromeIGStory#8]

**Comment by CaliAlec** [comment]
@ssd90 Are you talking about when you a mute a Story? I will had a different CSS class for muted Stories so they appear gray like they do in the app.

**Comment by ssd90** [comment]
@CaliAlec I can see two class; "seenStoryItem", "unseenStoryItem". Mute stories have purple circle.

**Comment by CaliAlec** [comment]
Fixed in https://github.com/CaliAlec/ChromeIGStory/commit/3a70a8c826dab8be775a3ca3a4a2865a132a4e38
