### ISSUE TITLE
Can be watching stories user's profile page? 

### ISSUE THREAD

**Issue by ssd90** [CaliAlec/ChromeIGStory#9]

**Comment by CaliAlec** [comment]
@ssd90 This feature already exists. https://github.com/CaliAlec/ChromeIGStory/commit/33fccb93c78a0335a1577b8f4fd6f41c3a84ff18

If you go to a user's profile page, it will show the colorful purple circle around their profile picture if they have a Story.

**Comment by ssd90** [comment]
@CaliAlec console error line:80  Error loading Story for user: " + JSON.stringify(error)

**Comment by barinali** [comment]
@CaliAlec unfortunately, it doesn't work. It gives error the following; 

`{"status": "fail", "message": "login_required"}`

response's request url is https://i.instagram.com/api/v1/feed/user/USERID/reel_media/.

By the way, I am logged to instagram.com. And I can see user stories on homepage.

**Comment by ebpo90** [comment]
same problem here, @barinali
at the profile page I've always receive a 400 error for the authentication
